### PR TITLE
Generate branch and jump table labels based on function name instead of address

### PR DESCRIPTION
**Pull request by cadmic**
This is to help match functions even if they're not in the same location in memory. Example:

```
glabel Player_ActionToModelGroup # 5
  addiu       $sp, $sp, -0x20
  sw          $ra, 0x14($sp)
  lui         $v1, 0x800F
  addu        $v1, $v1, $a1
  lbu         $v1, (0x800F7D64 & 0xFFFF)($v1)
  addiu       $at, $zero, 0x2
  bnel        $v1, $at, .LPlayer_ActionToModelGroup_2
   move       $v0, $v1
  jal         Player_IsChildWithHylianShield
   sw         $v1, 0x1C($sp)
  beqz        $v0, .LPlayer_ActionToModelGroup_1
   lw         $v1, 0x1C($sp)
  b           .LPlayer_ActionToModelGroup_2
   addiu      $v0, $zero, 0x1
.LPlayer_ActionToModelGroup_1:
  move        $v0, $v1
.LPlayer_ActionToModelGroup_2:
  lw          $ra, 0x14($sp)
  addiu       $sp, $sp, 0x20
  jr          $ra
   nop
```

I'm not sure how to test this more thoroughly, perhaps it does weird things with strange code or if there's already a label where the branch label should go

### CODE REVIEW

**Review by AngheloAlf — COMMENTED** [review]
I like this idea but I don't think we should change the default behavior, because spimdisasm is used in many projects, unconditionally changing this can be confusing for the end users.

What do you think about putting it behind a global setting instead? Take a look at `spimdisasm/common/GlobalConfig.py`

**Comment by AngheloAlf** [comment]
Good question. Maybe something like `SEQUENTIAL_BRANCH_LABELS`?

**Comment by AngheloAlf** [comment]
Actually, I think it would be better to move the logic of generating a name for the labels to `getDefaultName` (on `spimdisasm/common/ContextSymbols.py`), so we keep that logic centralized on one place.
You can add any extra members to the `ContextSymbol` class if you need them.

**Comment by cadmic** [comment]
Okay, I gave that a go. I've just realized though that I probably want this for jump table labels too (i.e. number all branch targets sequentially regardless of whether they're for direct or indirect branches). I'm not sure how to know the containing function or the index when jump tables labels are created. What's a good way to implement this?

**Comment by cadmic** [comment]
Never mind, it was pretty easy. Though I'm not sure what to call the flags now, or they should use the same flag

**Comment by AngheloAlf** [comment]
Cool!
I think a single option for both is better, I don't see an use case where you would enable one and not the other.
Maybe something like `SEQUENTIAL_LABEL_NAMES`?

**Comment by cadmic** [comment]
Okay, changed to 1 flag

**Pull request merged**
